backend:
  name: github
  repo: baboyiban/baboyiban.github.io
  branch: main
  pkce: true # Netlify 우회용 PKCE 인증 활성화
  app_id: 87802bc3afba4346adbe # 임시(Test)용 Oauth App ID. 실제로는 직접 발급받는 것이 좋습니다.

media_folder: "images"
public_folder: "/images"

# 설정: 프론트매터를 어떤 포맷으로 저장할 것인지 정의합니다.
collections:
  - name: "post"
    label: "포스트"
    label_singular: "포스트"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "제목", name: "title", widget: "string" }
      - { label: "작성일", name: "date", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false }
      - { label: "본문", name: "body", widget: "markdown" }
